### ISSUE TITLE
关于安装完驱动包，无法驱动ag-95夹爪的问题。

### ISSUE THREAD

**Issue by pibaopi** [DH-Robotics/dh_gripper_ros#2]
你好，在根据教程编译了AG95驱动包之后，我想要通过roslaunch dh_gripper_driver dh_gripper.launch
命令来驱动我的AG-95夹爪，运行后的终端显示如图所示
![终端](https://user-images.githubusercontent.com/77523889/144858929-17bcbdcd-dde4-47cf-a2e6-ac3c522963d0.png)
即使终端提示open successful,我依旧无法看见我的爪子被成功的初始化，没有看见他闭合打开，并且一直处于wait grip initialized状态，我不知道是怎么回事，这是我的dh_gripper.launch设置图
![dh-launch](https://user-images.githubusercontent.com/77523889/144859813-bad21195-97cd-4397-8987-6f492a193f0d.png)
请帮我看看是怎么回事，谢谢！

**Comment by DH-Robotics** [comment]
您好，
    根据您截取的图片可能是以下原因：
    您手上的应该是带一个黑色的通讯盒的AG95版本，走USB或者TCP/IP协议，请修改launch文件中的Model 为 AG95_CAN，port则按照您的系统识别的USB口进行修改，一般是/dev/ttyACM*（注意chmod修改权限）
    如果还有其他问题，您可以联系您购买该产品的销售寻求技术支持。

祝好，
深圳市大寰机器人
------------------------------------------------------------------
发件人：pibaopi ***@***.***>
发送时间：2021年12月6日(星期一) 22:04
收件人：DH-Robotics/dh_gripper_ros ***@***.***>
抄　送：Subscribed ***@***.***>
主　题：[DH-Robotics/dh_gripper_ros] 关于安装完驱动包，无法驱动ag-95夹爪的问题。 (Issue #2)

你好，在根据教程编译了AG95驱动包之后，我想要通过roslaunch dh_gripper_driver dh_gripper.launch
 命令来驱动我的AG-95夹爪，运行后的终端显示如图所示
[终端]
 即使终端提示open successful,我依旧无法看见我的爪子被成功的初始化，没有看见他闭合打开，并且一直处于wait grip initialized状态，我不知道是怎么回事，这是我的dh_gripper.launch设置图
[Uploading dh-launch.png…]
 请帮我看看是怎么回事，谢谢！
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DH-Robotics** [comment]
您好, 
    由于AG95是多连杆式的结构，会变传动比，并且整机高度还会随手指张开距离而变化，所以我们的位置百分比是指的内部电机的行程百分比，不对应实际的夹爪开度。而具体开度您可以参考这个附件。

**Comment by pibaopi** [comment]
@DH-Robotics 谢谢您的解答，但是您所说的附件是在哪一个呢，这边并没有看到所谓的附件。

**Comment by DH-Robotics** [comment]
这里没法上传附件，我已经将文件添加到了仓库中，您可以下拉最新的源

**Comment by pibaopi** [comment]
@DH-Robotics 已经看见了，非常感谢您的帮助！
